<Project>
  <PropertyGroup>
    <VersionPrefix>0.1.0</VersionPrefix>
    <Company>Everty</Company>
    <Product>EvertyGame</Product>
    <RepositoryUrl>https://github.com/vaalimusic/EvertyGame</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CI)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
