// =============================================================================
// EVRT2 — AuthTag (HMAC-SHA256) + ENCRYPTED payload — ROADMAP.md Phase 4.2/4.3
// Spec: evrt2/spec/EVRT2_PACKET.md § AuthTag, ENCRYPTED flag
// Author of the standard: Arthur Valiev. Rust implementation below.
// =============================================================================
//
//! `EVRT2_PACKET.md`'s AuthTag field: "32-bit truncated HMAC-SHA256 of
//! header+payload". This module computes and verifies it against an
//! already-encoded wire buffer (32-byte header + payload) — it does not
//! know or care about packet semantics, only bytes. It also implements the
//! `ENCRYPTED` flag (Phase 4.3) — see that section below for the one
//! deliberate deviation from the spec's literal wording.
//!
//! **Honest scope note on key exchange**: this module only does the MAC
//! and cipher operations themselves. The session key it operates on is
//! generated by the host (`generate_session_key`) and handed to the client
//! over whatever channel `evrt2_experiment.rs` already uses to announce the
//! UDP endpoints (the same TCP relay connection the RustDesk-compatible
//! handshake uses) — its confidentiality is therefore only as strong as
//! that channel's own security, which in an unattended/no-password test
//! session can be plaintext (see `EVRT2_SECURITY.md`'s own note on this).
//! This is not a new weakness EVRT2 introduces — EVRT1's
//! `evrt_session_token` already travels the identical path — but it means
//! AuthTag/ENCRYPTED currently defend against a *third party* who only
//! sees the UDP traffic, not against someone who can also read the TCP
//! control channel during key exchange.

use dryoc::classic::crypto_secretbox::{crypto_secretbox_easy, crypto_secretbox_open_easy};
use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};

pub type SessionKey = [u8; 32];

/// Byte offset of the AuthTag field within the 32-byte packet header (see
/// `evrt2_packet::PacketHeader::encode` — Magic(4)+Ver/Type(1)+Mode(1)+
/// Flags(2)+FrameId(4)+PacketIndex(2)+PacketCount(2)+PresentationTime(8)+
/// FEC Group/Idx/Total/Reserved(4) = 28, then AuthTag(4)).
const AUTH_TAG_OFFSET: usize = 28;
const AUTH_TAG_LEN: usize = 4;

/// Generates a fresh 32-byte session key from OS-sourced entropy. Uses two
/// `Uuid::new_v4()` draws (each backed by `getrandom`, the same CSPRNG
/// source the rest of this codebase already trusts for `evrt_session_token`)
/// concatenated to 32 bytes, rather than pulling in a second RNG crate for
/// one call site.
pub fn generate_session_key() -> SessionKey {
    let mut key = [0u8; 32];
    key[..16].copy_from_slice(uuid::Uuid::new_v4().as_bytes());
    key[16..].copy_from_slice(uuid::Uuid::new_v4().as_bytes());
    key
}

pub fn key_to_hex(key: &SessionKey) -> String {
    key.iter().map(|b| format!("{b:02x}")).collect()
}

pub fn key_from_hex(s: &str) -> Option<SessionKey> {
    let s = s.trim();
    if s.len() != 64 {
        return None;
    }
    let mut key = [0u8; 32];
    for i in 0..32 {
        key[i] = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).ok()?;
    }
    Some(key)
}

fn hmac_full(key: &SessionKey, wire_with_zeroed_tag: &[u8]) -> [u8; 32] {
    let mut mac = Hmac::<Sha256>::new_from_slice(key).expect("HMAC accepts any key length");
    mac.update(wire_with_zeroed_tag);
    mac.finalize().into_bytes().into()
}

/// Signs an already-encoded wire packet (32-byte header + payload) in
/// place: zeroes the AuthTag field, computes HMAC-SHA256 over the whole
/// buffer, writes the first 4 bytes back into the AuthTag field. No-op
/// (returns immediately) if `wire` is shorter than the header — malformed
/// input the caller built incorrectly, not this function's job to report.
pub fn sign_packet(key: &SessionKey, wire: &mut [u8]) {
    if wire.len() < AUTH_TAG_OFFSET + AUTH_TAG_LEN {
        return;
    }
    wire[AUTH_TAG_OFFSET..AUTH_TAG_OFFSET + AUTH_TAG_LEN].fill(0);
    let tag = hmac_full(key, wire);
    wire[AUTH_TAG_OFFSET..AUTH_TAG_OFFSET + AUTH_TAG_LEN].copy_from_slice(&tag[..AUTH_TAG_LEN]);
}

/// Verifies a received wire packet's AuthTag against `key`. Returns `false`
/// (never panics) on anything short of an exact match, including a
/// too-short buffer. Constant-time-ish by virtue of comparing the full
/// 4-byte tag with `==` on a stack array — not claiming side-channel
/// hardness beyond what that gives; the threat model here is a forged UDP
/// packet from a network attacker, not a timing side-channel from a
/// co-located process.
pub fn verify_packet(key: &SessionKey, wire: &[u8]) -> bool {
    if wire.len() < AUTH_TAG_OFFSET + AUTH_TAG_LEN {
        return false;
    }
    let received_tag = &wire[AUTH_TAG_OFFSET..AUTH_TAG_OFFSET + AUTH_TAG_LEN];
    let mut zeroed = wire.to_vec();
    zeroed[AUTH_TAG_OFFSET..AUTH_TAG_OFFSET + AUTH_TAG_LEN].fill(0);
    let expected = hmac_full(key, &zeroed);
    received_tag == &expected[..AUTH_TAG_LEN]
}

// ── ENCRYPTED flag (ROADMAP.md Phase 4.3) ───────────────────────────────────

/// **Deviation from EVRT2_PACKET.md, stated up front**: the spec names
/// AES-GCM-256 for the `ENCRYPTED` flag. This implements it with NaCl
/// `secretbox` (XSalsa20-Poly1305) instead — the same AEAD primitive
/// `src/crypto.rs` already uses (and this codebase already trusts) for the
/// RustDesk-compatible TCP relay's own encryption, rather than adding a
/// second, unaudited-in-this-codebase cipher family purely to match one
/// spec sentence. Both are AEAD constructions with equivalent security
/// properties for this use case — see EVRT2_SECURITY.md for the full
/// reasoning.
const SECRETBOX_MAC_LEN: usize = 16;
const NONCE_LEN: usize = 24;

/// Derives a key for `ENCRYPTED` payload encryption from the same session
/// key AuthTag uses — kept as a *separate* key (not the raw session key)
/// via a labeled hash, so a compromise of one primitive's key material
/// doesn't directly hand over the other's. Cheap enough to call per-packet
/// rather than caching, though callers may cache it if it matters.
pub fn derive_encryption_key(session_key: &SessionKey) -> SessionKey {
    let mut hasher = Sha256::new();
    hasher.update(session_key);
    hasher.update(b"evrt2-encrypt-v1");
    hasher.finalize().into()
}

/// Deterministic per-packet nonce, derived from the packet's own header
/// bytes (everything except the AuthTag field, which isn't set yet at
/// encryption time — encryption happens before signing, matching
/// Encrypt-then-MAC). FrameId+PacketIndex+PacketCount+PresentationTimeUs+
/// FEC fields together are unique per packet within a session for any
/// realistic session length, which is exactly what a nonce needs (never
/// reused under the same key) — this avoids needing a dedicated nonce
/// field in an already wire-fixed 32-byte header.
fn derive_nonce(header_minus_auth_tag: &[u8]) -> [u8; NONCE_LEN] {
    let mut hasher = Sha256::new();
    hasher.update(header_minus_auth_tag);
    let digest = hasher.finalize();
    let mut nonce = [0u8; NONCE_LEN];
    nonce.copy_from_slice(&digest[..NONCE_LEN]);
    nonce
}

/// Encrypts `wire`'s payload (everything after the 32-byte header) in
/// place, setting the `ENCRYPTED` flag bit in the header first (so the
/// nonce derivation and the eventual AuthTag both cover the flag's final
/// value). Grows `wire` by `SECRETBOX_MAC_LEN` (16 bytes) — callers that
/// budget fragment sizes against `MAX_PAYLOAD` need to account for this;
/// see `evrt2_session`'s wiring. No-op on a too-short buffer.
pub fn encrypt_payload(enc_key: &SessionKey, wire: &mut Vec<u8>) {
    if wire.len() < AUTH_TAG_OFFSET {
        return;
    }
    let flags = u16::from_be_bytes([wire[6], wire[7]]) | (1 << 3); // flags::ENCRYPTED
    wire[6] = (flags >> 8) as u8;
    wire[7] = (flags & 0xFF) as u8;

    let nonce = derive_nonce(&wire[..AUTH_TAG_OFFSET]);
    let plaintext = wire[AUTH_TAG_OFFSET + AUTH_TAG_LEN..].to_vec();
    let mut ciphertext = vec![0u8; plaintext.len() + SECRETBOX_MAC_LEN];
    // crypto_secretbox_easy only fails on impossible buffer sizes (already
    // guaranteed correct here — see crypto.rs's identical `let _ =` pattern).
    let _ = crypto_secretbox_easy(&mut ciphertext, &plaintext, &nonce, enc_key);
    wire.truncate(AUTH_TAG_OFFSET + AUTH_TAG_LEN);
    wire.extend_from_slice(&ciphertext);
}

/// Decrypts `wire`'s payload if the `ENCRYPTED` flag is set, returning the
/// plaintext payload bytes. Returns the payload unchanged (as owned bytes)
/// if the flag is clear — a caller can treat this function's output as
/// "the real payload" unconditionally without checking the flag itself
/// first. Returns `None` on a too-short buffer or a failed decrypt
/// (wrong key, corrupted ciphertext, or a claimed-encrypted packet whose
/// MAC doesn't verify).
pub fn decrypt_payload(enc_key: &SessionKey, wire: &[u8]) -> Option<Vec<u8>> {
    if wire.len() < AUTH_TAG_OFFSET + AUTH_TAG_LEN {
        return None;
    }
    let flags = u16::from_be_bytes([wire[6], wire[7]]);
    let ciphertext = &wire[AUTH_TAG_OFFSET + AUTH_TAG_LEN..];
    if flags & (1 << 3) == 0 {
        // flags::ENCRYPTED not set — not encrypted, pass through as-is.
        return Some(ciphertext.to_vec());
    }
    if ciphertext.len() < SECRETBOX_MAC_LEN {
        return None;
    }
    let nonce = derive_nonce(&wire[..AUTH_TAG_OFFSET]);
    let mut plaintext = vec![0u8; ciphertext.len() - SECRETBOX_MAC_LEN];
    crypto_secretbox_open_easy(&mut plaintext, ciphertext, &nonce, enc_key).ok()?;
    Some(plaintext)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_keys_are_not_all_zero_and_differ_each_call() {
        let a = generate_session_key();
        let b = generate_session_key();
        assert_ne!(a, [0u8; 32], "must not silently produce a zero key");
        assert_ne!(
            a, b,
            "two draws must not collide (would indicate a broken RNG source)"
        );
    }

    #[test]
    fn hex_roundtrip() {
        let key = generate_session_key();
        let hex = key_to_hex(&key);
        assert_eq!(hex.len(), 64);
        assert_eq!(key_from_hex(&hex), Some(key));
    }

    #[test]
    fn key_from_hex_rejects_wrong_length_and_bad_chars() {
        assert_eq!(key_from_hex("abcd"), None);
        assert_eq!(key_from_hex(&"zz".repeat(32)), None);
    }

    fn fake_wire(header_len: usize, payload_len: usize) -> Vec<u8> {
        let mut w = vec![0u8; header_len + payload_len];
        // Give the header some non-zero content so a broken implementation
        // that e.g. only hashes the payload would still fail the "changes
        // when header changes" test below.
        for (i, b) in w.iter_mut().enumerate().take(header_len) {
            *b = (i % 256) as u8;
        }
        w
    }

    #[test]
    fn sign_then_verify_round_trips() {
        let key = generate_session_key();
        let mut wire = fake_wire(32, 100);
        sign_packet(&key, &mut wire);
        assert!(verify_packet(&key, &wire));
    }

    #[test]
    fn tampered_payload_fails_verification() {
        let key = generate_session_key();
        let mut wire = fake_wire(32, 100);
        sign_packet(&key, &mut wire);
        wire[50] ^= 0xFF; // flip a payload byte after signing
        assert!(!verify_packet(&key, &wire));
    }

    #[test]
    fn tampered_header_fails_verification() {
        let key = generate_session_key();
        let mut wire = fake_wire(32, 100);
        sign_packet(&key, &mut wire);
        wire[10] ^= 0xFF; // flip a header byte after signing
        assert!(!verify_packet(&key, &wire));
    }

    #[test]
    fn wrong_key_fails_verification() {
        let key_a = generate_session_key();
        let key_b = generate_session_key();
        let mut wire = fake_wire(32, 100);
        sign_packet(&key_a, &mut wire);
        assert!(!verify_packet(&key_b, &wire));
    }

    #[test]
    fn truncated_wire_never_panics_and_fails_verification() {
        let key = generate_session_key();
        assert!(!verify_packet(&key, &[]));
        assert!(!verify_packet(&key, &[0u8; 10]));
        assert!(!verify_packet(&key, &[0u8; 31])); // one byte short of the header
    }

    #[test]
    fn sign_on_undersized_buffer_does_not_panic() {
        let key = generate_session_key();
        let mut short = vec![0u8; 5];
        sign_packet(&key, &mut short); // must not panic — no-op per doc comment
        assert_eq!(short, vec![0u8; 5]);
    }

    #[test]
    fn changing_payload_produces_a_different_tag_with_overwhelming_probability() {
        // Not a formal collision-resistance proof — just confirms the tag
        // isn't accidentally constant/ignoring the input entirely. Byte 20
        // sits inside PresentationTimeUs (header, but outside the 28..32
        // AuthTag range `sign_packet` always zeroes before hashing — a
        // byte from *inside* that range would be reset before it could
        // affect the tag, which is exactly the bug this comment is here to
        // prevent re-introducing).
        let key = generate_session_key();
        let mut wire_a = fake_wire(32, 20);
        let mut wire_b = fake_wire(32, 20);
        wire_b[20] = 0xFF;
        sign_packet(&key, &mut wire_a);
        sign_packet(&key, &mut wire_b);
        assert_ne!(
            &wire_a[AUTH_TAG_OFFSET..AUTH_TAG_OFFSET + AUTH_TAG_LEN],
            &wire_b[AUTH_TAG_OFFSET..AUTH_TAG_OFFSET + AUTH_TAG_LEN]
        );
    }

    // ── ENCRYPTED flag (Phase 4.3) ──────────────────────────────────────────

    #[test]
    fn derived_encryption_key_differs_from_session_key() {
        let session_key = generate_session_key();
        let enc_key = derive_encryption_key(&session_key);
        assert_ne!(
            enc_key, session_key,
            "must be a genuinely different key, not the raw session key"
        );
    }

    #[test]
    fn derived_encryption_key_is_deterministic() {
        let session_key = generate_session_key();
        assert_eq!(
            derive_encryption_key(&session_key),
            derive_encryption_key(&session_key)
        );
    }

    #[test]
    fn encrypt_then_decrypt_round_trips_the_payload() {
        let enc_key = derive_encryption_key(&generate_session_key());
        let mut wire = fake_wire(32, 100);
        let original_payload = wire[32..].to_vec();
        encrypt_payload(&enc_key, &mut wire);
        let decrypted = decrypt_payload(&enc_key, &wire).expect("must decrypt");
        assert_eq!(decrypted, original_payload);
    }

    #[test]
    fn encryption_sets_the_encrypted_flag_bit() {
        let enc_key = derive_encryption_key(&generate_session_key());
        let mut wire = fake_wire(32, 50);
        let flags_before = u16::from_be_bytes([wire[6], wire[7]]);
        assert_eq!(
            flags_before & (1 << 3),
            0,
            "test fixture must start unencrypted"
        );
        encrypt_payload(&enc_key, &mut wire);
        let flags_after = u16::from_be_bytes([wire[6], wire[7]]);
        assert_ne!(flags_after & (1 << 3), 0, "ENCRYPTED flag bit must be set");
    }

    #[test]
    fn ciphertext_does_not_contain_the_plaintext() {
        let enc_key = derive_encryption_key(&generate_session_key());
        let mut wire = fake_wire(32, 50);
        // fake_wire fills the header with i%256 but leaves payload zeroed —
        // give it real, non-trivial content to search for.
        for (i, b) in wire[32..].iter_mut().enumerate() {
            *b = (i * 7 % 256) as u8;
        }
        let plaintext = wire[32..].to_vec();
        encrypt_payload(&enc_key, &mut wire);
        let ciphertext = &wire[32..];
        assert_ne!(
            ciphertext,
            &plaintext[..],
            "ciphertext must not equal plaintext"
        );
        // Not a rigorous entropy test — just confirms the encrypted bytes
        // aren't a trivial identity/XOR-with-zero no-op.
    }

    #[test]
    fn wrong_key_fails_to_decrypt() {
        let enc_key_a = derive_encryption_key(&generate_session_key());
        let enc_key_b = derive_encryption_key(&generate_session_key());
        let mut wire = fake_wire(32, 50);
        encrypt_payload(&enc_key_a, &mut wire);
        assert_eq!(decrypt_payload(&enc_key_b, &wire), None);
    }

    #[test]
    fn tampered_ciphertext_fails_to_decrypt() {
        let enc_key = derive_encryption_key(&generate_session_key());
        let mut wire = fake_wire(32, 50);
        encrypt_payload(&enc_key, &mut wire);
        let last = wire.len() - 1;
        wire[last] ^= 0xFF;
        assert_eq!(decrypt_payload(&enc_key, &wire), None);
    }

    #[test]
    fn unencrypted_wire_passes_through_decrypt_unchanged() {
        let enc_key = derive_encryption_key(&generate_session_key());
        let wire = fake_wire(32, 50);
        let expected_payload = wire[32..].to_vec();
        let result =
            decrypt_payload(&enc_key, &wire).expect("unencrypted payload must still decode");
        assert_eq!(result, expected_payload);
    }

    #[test]
    fn each_packet_gets_a_different_nonce_because_headers_differ() {
        // Two packets with different content at byte 20 (inside the header,
        // e.g. differing PresentationTimeUs) must encrypt to different
        // ciphertext even with identical plaintext payloads and the same
        // key — proof the nonce isn't accidentally constant.
        let enc_key = derive_encryption_key(&generate_session_key());
        let mut wire_a = fake_wire(32, 20);
        let mut wire_b = fake_wire(32, 20);
        wire_b[20] = wire_b[20].wrapping_add(1);
        for i in 0..20 {
            wire_a[32 + i] = i as u8;
            wire_b[32 + i] = i as u8;
        }
        encrypt_payload(&enc_key, &mut wire_a);
        encrypt_payload(&enc_key, &mut wire_b);
        assert_ne!(
            &wire_a[32..],
            &wire_b[32..],
            "same plaintext, different header, must not produce identical ciphertext"
        );
    }

    #[test]
    fn encrypt_grows_wire_by_mac_length() {
        let enc_key = derive_encryption_key(&generate_session_key());
        let mut wire = fake_wire(32, 50);
        let len_before = wire.len();
        encrypt_payload(&enc_key, &mut wire);
        assert_eq!(wire.len(), len_before + SECRETBOX_MAC_LEN);
    }
}
